name: lost
description: A top down maze game.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flame: 1.10.0
  flame_audio: 2.1.2
  flame_forge2d: 0.15.1
  flutter:
    sdk: flutter
  maze_builder: 1.0.1

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter
  icons_launcher: 2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/

icons_launcher:
  image_path: "assets/images/Lost-Icon.png"
  platforms:
    linux:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    android:
      enable: false
    ios:
      enable: false
    macos:
      enable: false
